In [3]:
!pip install scikit-learn


Defaulting to user installation because normal site-packages is not writeable


In [18]:
from sklearn.datasets import load_iris
for i in range(len(load_iris().target)):
    print(load_iris().target[i]," ",load_iris().data[i])

print(load_iris().data)

print(load_iris().target)



0   [5.1 3.5 1.4 0.2]
0   [4.9 3.  1.4 0.2]
0   [4.7 3.2 1.3 0.2]
0   [4.6 3.1 1.5 0.2]
0   [5.  3.6 1.4 0.2]
0   [5.4 3.9 1.7 0.4]
0   [4.6 3.4 1.4 0.3]
0   [5.  3.4 1.5 0.2]
0   [4.4 2.9 1.4 0.2]
0   [4.9 3.1 1.5 0.1]
0   [5.4 3.7 1.5 0.2]
0   [4.8 3.4 1.6 0.2]
0   [4.8 3.  1.4 0.1]
0   [4.3 3.  1.1 0.1]
0   [5.8 4.  1.2 0.2]
0   [5.7 4.4 1.5 0.4]
0   [5.4 3.9 1.3 0.4]
0   [5.1 3.5 1.4 0.3]
0   [5.7 3.8 1.7 0.3]
0   [5.1 3.8 1.5 0.3]
0   [5.4 3.4 1.7 0.2]
0   [5.1 3.7 1.5 0.4]
0   [4.6 3.6 1.  0.2]
0   [5.1 3.3 1.7 0.5]
0   [4.8 3.4 1.9 0.2]
0   [5.  3.  1.6 0.2]
0   [5.  3.4 1.6 0.4]
0   [5.2 3.5 1.5 0.2]
0   [5.2 3.4 1.4 0.2]
0   [4.7 3.2 1.6 0.2]
0   [4.8 3.1 1.6 0.2]
0   [5.4 3.4 1.5 0.4]
0   [5.2 4.1 1.5 0.1]
0   [5.5 4.2 1.4 0.2]
0   [4.9 3.1 1.5 0.2]
0   [5.  3.2 1.2 0.2]
0   [5.5 3.5 1.3 0.2]
0   [4.9 3.6 1.4 0.1]
0   [4.4 3.  1.3 0.2]
0   [5.1 3.4 1.5 0.2]
0   [5.  3.5 1.3 0.3]
0   [4.5 2.3 1.3 0.3]
0   [4.4 3.2 1.3 0.2]
0   [5.  3.5 1.6 0.6]
0   [5.1 3.8 1.9 0.4]
0   [4.8 3

In [14]:
# dataset ko randomize - rows

In [15]:
# split the dataset into data and targets similar to load_iris()


data=[]
target =[]

In [4]:
import csv
data=[]
target =[]
with open('clustering_table.csv', mode ='r')as file:
  csvFile = csv.reader(file)
  for lines in csvFile:
        target.append(lines[0])
        data.append(lines[1:15:])

target = target[1::]
data = data[1::]
for i in data:
    print(i)
print(target)



['1', '5', '2', '3', '4', '3', '2', '4', '1', '4', '0', '1', '1', '0']
['2', '6', '4', '4', '3', '4', '3', '1', '0', '1', '0', '1', '0', '0']
['3', '4', '7', '3', '3', '6', '1', '3', '2', '0', '0', '0', '0', '0']
['4', '6', '4', '5', '4', '3', '0', '1', '1', '2', '3', '2', '0', '0']
['5', '7', '5', '4', '2', '1', '2', '1', '1', '1', '1', '0', '1', '0']
['6', '7', '4', '3', '3', '4', '2', '5', '3', '2', '1', '0', '0', '0']
['7', '6', '7', '3', '6', '4', '2', '0', '1', '0', '0', '1', '0', '1']
['8', '4', '4', '6', '2', '3', '2', '2', '0', '1', '0', '1', '0', '0']
['9', '7', '6', '6', '4', '4', '2', '5', '0', '1', '1', '0', '1', '1']
['10', '4', '5', '5', '3', '1', '3', '0', '2', '2', '2', '1', '2', '0']
['11', '3', '10', '6', '1', '3', '3', '2', '1', '1', '0', '0', '1', '0']
['12', '4', '7', '1', '4', '2', '1', '2', '1', '2', '2', '1', '0', '1']
['13', '7', '5', '3', '4', '2', '2', '1', '0', '0', '1', '1', '0', '1']
['14', '4', '8', '6', '3', '4', '4', '4', '1', '1', '1', '0', '1', '0']


In [5]:
data_int =[]
target_int =[]

for i in data:
    data_int_row=[]
    for j in i:
        data_int_row.append(int(j))
    data_int.append(data_int_row)

print(data_int)


s = target
mydict={}
i = 0
for item in s:
    if(i>0 and item in mydict):
        continue
    else:    
       i = i+1
       mydict[item] = i

k=[]
for item in s:
    k.append(mydict[item])

print(k)
target_int = k

[[1, 5, 2, 3, 4, 3, 2, 4, 1, 4, 0, 1, 1, 0], [2, 6, 4, 4, 3, 4, 3, 1, 0, 1, 0, 1, 0, 0], [3, 4, 7, 3, 3, 6, 1, 3, 2, 0, 0, 0, 0, 0], [4, 6, 4, 5, 4, 3, 0, 1, 1, 2, 3, 2, 0, 0], [5, 7, 5, 4, 2, 1, 2, 1, 1, 1, 1, 0, 1, 0], [6, 7, 4, 3, 3, 4, 2, 5, 3, 2, 1, 0, 0, 0], [7, 6, 7, 3, 6, 4, 2, 0, 1, 0, 0, 1, 0, 1], [8, 4, 4, 6, 2, 3, 2, 2, 0, 1, 0, 1, 0, 0], [9, 7, 6, 6, 4, 4, 2, 5, 0, 1, 1, 0, 1, 1], [10, 4, 5, 5, 3, 1, 3, 0, 2, 2, 2, 1, 2, 0], [11, 3, 10, 6, 1, 3, 3, 2, 1, 1, 0, 0, 1, 0], [12, 4, 7, 1, 4, 2, 1, 2, 1, 2, 2, 1, 0, 1], [13, 7, 5, 3, 4, 2, 2, 1, 0, 0, 1, 1, 0, 1], [14, 4, 8, 6, 3, 4, 4, 4, 1, 1, 1, 0, 1, 0], [15, 5, 4, 7, 3, 3, 3, 2, 2, 0, 3, 1, 0, 1], [16, 6, 3, 2, 4, 5, 2, 1, 2, 2, 1, 2, 0, 0], [17, 5, 5, 5, 4, 2, 2, 2, 3, 1, 0, 1, 0, 0], [18, 5, 5, 3, 3, 1, 2, 1, 1, 2, 3, 0, 0, 1], [19, 5, 0, 5, 3, 3, 3, 2, 2, 3, 0, 0, 0, 0], [1, 6, 6, 5, 3, 3, 3, 1, 2, 0, 1, 0, 0, 0], [2, 4, 6, 5, 5, 2, 3, 1, 4, 0, 3, 0, 0, 0], [3, 6, 4, 4, 3, 4, 1, 2, 0, 1, 1, 1, 1, 1], [4, 8, 4, 3, 3, 3, 1

In [6]:
#knn classification
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

X = data
y = target
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size=0.4, random_state=7)
sc= StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)
knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)
y_pred = knn.predict(X_test)
# print("test input")
# print(X_test)
print("predicted output")
print(y_pred)
print("actual output")
print(y_test)
print("accuracy: %.3f"% accuracy_score(y_pred,y_test))
print("confusion matrix:\n" ,confusion_matrix(y_pred,y_test))
print("classification report:\n",classification_report(y_pred,y_test))

predicted output
['rc4' 'blowfish' 'des3' 'rc4' 'rsa' 'rc4' 'rc4' 'aes' 'aes' 'des3' 'aes'
 'aes' 'rsa' 'rsa' 'blowfish' 'des3' 'rsa' 'rc4' 'blowfish' 'rc4' 'des3'
 'blowfish' 'des3' 'blowfish' 'blowfish' 'blowfish' 'rc4' 'rsa' 'blowfish'
 'rc4' 'des3' 'blowfish' 'rc4' 'aes' 'rc4' 'aes' 'rc4' 'rc4']
actual output
['des3', 'rsa', 'rc4', 'rc4', 'des3', 'aes', 'blowfish', 'des3', 'des3', 'des3', 'aes', 'des3', 'rc4', 'aes', 'rc4', 'blowfish', 'aes', 'rc4', 'aes', 'rsa', 'aes', 'aes', 'rc4', 'aes', 'rc4', 'rsa', 'rsa', 'des3', 'blowfish', 'blowfish', 'blowfish', 'des3', 'blowfish', 'des3', 'des3', 'blowfish', 'blowfish', 'rsa']
accuracy: 0.132
confusion matrix:
 [[1 1 4 0 0]
 [3 1 1 2 2]
 [1 2 1 2 0]
 [1 4 2 2 3]
 [2 0 2 1 0]]
classification report:
               precision    recall  f1-score   support

         aes       0.12      0.17      0.14         6
    blowfish       0.12      0.11      0.12         9
        des3       0.10      0.17      0.12         6
         rc4       0.29   

In [7]:
import numpy as np
import pandas as pd
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.datasets import load_iris
iris = load_iris()
X = data
y = target
X_train,X_test,y_train,y_test = train_test_split(X, y, test_size=0.2, random_state=1)
sc = StandardScaler()
sc.fit(X_train)
X_train = sc.transform(X_train)
X_test = sc.transform(X_test)
svm = SVC(kernel = "linear")
svm.fit(X_train,y_train)
y_pred = svm.predict(X_test)
# print("test input")
# print(X_test)
print("predicted output")
print(y_pred)
print("actual output")
print(y_test)
print("accuracy: %.3f"% accuracy_score(y_pred,y_test))
print("confusion matrix:\n" ,confusion_matrix(y_pred,y_test))
print("classification report:\n",classification_report(y_pred,y_test))

predicted output
['des3' 'aes' 'aes' 'blowfish' 'rc4' 'blowfish' 'des3' 'aes' 'rsa' 'des3'
 'rc4' 'aes' 'aes' 'des3' 'des3' 'rc4' 'blowfish' 'rsa' 'rc4']
actual output
['blowfish', 'des3', 'blowfish', 'rc4', 'rsa', 'blowfish', 'rsa', 'blowfish', 'rsa', 'rsa', 'rc4', 'des3', 'rc4', 'rsa', 'des3', 'blowfish', 'blowfish', 'aes', 'aes']
accuracy: 0.263
confusion matrix:
 [[0 2 2 1 0]
 [0 2 0 1 0]
 [0 1 1 0 3]
 [1 1 0 1 1]
 [1 0 0 0 1]]
classification report:
               precision    recall  f1-score   support

         aes       0.00      0.00      0.00         5
    blowfish       0.33      0.67      0.44         3
        des3       0.33      0.20      0.25         5
         rc4       0.33      0.25      0.29         4
         rsa       0.20      0.50      0.29         2

    accuracy                           0.26        19
   macro avg       0.24      0.32      0.25        19
weighted avg       0.23      0.26      0.23        19



In [8]:
import pandas as pd
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.datasets import load_iris
iris = load_iris()
X = data_int
y = target_int
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
linear_r = linear_model.LogisticRegression()
linear_r.fit(X_train, y_train)
y_pred = linear_r.predict(X_test)
# print("test input")
# print(X_test)
print("predicted output")
print(y_pred)
print("actual output")
print(y_test)


predicted output
[4 3 1 3 3 4 2 2 2 1 2 4 5 4 5 2 3 4 4 2 5 1 5 5 5 5 4 3 3 4 2 5]
actual output
[4, 2, 4, 4, 1, 2, 3, 3, 1, 3, 5, 3, 5, 3, 1, 1, 1, 2, 3, 4, 1, 5, 5, 2, 2, 1, 3, 3, 2, 4, 1, 5]


/home/christina/.local/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [35]:
#
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

iris = load_iris()
X = data
y = target
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
dt = DecisionTreeClassifier(criterion='gini', max_depth=3, random_state=0)
dt.fit(X_train, y_train)
y_pred = dt.predict(X_test)
# print("test input")
# print(X_test)
print("predicted output")
print(y_pred)
print("actual output")
print(y_test)
print("accuracy: %.3f"% accuracy_score(y_pred,y_test))
print("confusion matrix:\n" ,confusion_matrix(y_pred,y_test))
print("classification report:\n",classification_report(y_pred,y_test))


predicted output
['blowfish' 'des3' 'des3' 'rsa' 'rsa' 'blowfish' 'des3' 'blowfish' 'des3'
 'blowfish' 'des3' 'blowfish' 'rc4' 'rc4' 'des3' 'des3' 'blowfish' 'rc4'
 'blowfish' 'des3' 'rsa' 'rsa' 'des3' 'des3' 'des3' 'blowfish' 'des3'
 'blowfish' 'des3' 'des3' 'des3' 'blowfish']
actual output
['rc4', 'des3', 'rc4', 'rc4', 'aes', 'des3', 'blowfish', 'blowfish', 'aes', 'blowfish', 'rsa', 'blowfish', 'rsa', 'blowfish', 'aes', 'aes', 'aes', 'des3', 'blowfish', 'rc4', 'aes', 'rsa', 'rsa', 'des3', 'des3', 'aes', 'blowfish', 'blowfish', 'des3', 'rc4', 'aes', 'rsa']
accuracy: 0.312
confusion matrix:
 [[0 0 0 0 0]
 [2 5 1 1 1]
 [4 2 4 3 2]
 [0 1 1 0 1]
 [2 0 0 1 1]]
classification report:
               precision    recall  f1-score   support

         aes       0.00      0.00      0.00         0
    blowfish       0.62      0.50      0.56        10
        des3       0.67      0.27      0.38        15
         rc4       0.00      0.00      0.00         3
         rsa       0.20      0.25      0

/home/christina/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/christina/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/home/christina/.local/lib/python3.10/site-packages/sklearn/metrics/_classification.py:1531: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [61]:
from sklearn.naive_bayes import GaussianNB, BernoulliNB, MultinomialNB
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
from sklearn.datasets import load_iris
iris = load_iris()
X = data_int
y = target_int
print(len(X)," ",len(y))
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)
nb = GaussianNB()
nb.fit(X_train, y_train)
y_pred = nb.predict(X_test)
# print("test input")
# print(X_test)
print("predicted output")
print(y_pred)
print("actual output")
print(y_test)
print("accuracy: %.3f"% accuracy_score(y_pred,y_test))
print("confusion matrix:\n" ,confusion_matrix(y_pred,y_test))
print("classification report:\n",classification_report(y_pred,y_test))

95   95
predicted output
[2 4 1 5 4 4 2 5 5 1 2 3 5 4 5 2 3 5 1 2 5 1 5 2 5 5 4 3 5 5 2 5]
actual output
[4, 2, 4, 4, 1, 2, 3, 3, 1, 3, 5, 3, 5, 3, 1, 1, 1, 2, 3, 4, 1, 5, 5, 2, 2, 1, 3, 3, 2, 4, 1, 5]
accuracy: 0.188
confusion matrix:
 [[0 0 2 1 1]
 [2 1 1 2 1]
 [1 0 2 0 0]
 [1 2 2 0 0]
 [4 3 1 2 3]]
classification report:
               precision    recall  f1-score   support

           1       0.00      0.00      0.00         4
           2       0.17      0.14      0.15         7
           3       0.25      0.67      0.36         3
           4       0.00      0.00      0.00         5
           5       0.60      0.23      0.33        13

    accuracy                           0.19        32
   macro avg       0.20      0.21      0.17        32
weighted avg       0.30      0.19      0.20        32

